run:
  timeout: 5m
  tests: true
  concurrency: 4

issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - unconvert
    - prealloc
    - bodyclose
    - gofmt

linters-settings:
  misspell:
    locale: US
